language: groovy

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  - TERM=dumb

before_install:
  - chmod +x gradlew

script: ./gradlew clean build jacocoTestReport

after_success: ./gradlew jacocoRootReport coveralls assembleReleaseDist
